### ISSUE TITLE
Update z-band zero-points for each amplifier

### ISSUE THREAD

**Issue by djschlegel** [legacysurvey/obsbot#15]
Arjun has measured the following z-band zero-points from photometric good-seeing
frames on the night of 9/10 Feb 2016 as follows:
im4:  26.406
im7: 26.609
im11: 26.556
im16: 26.499
Since it's not measured for the other 12 amps, just use the average of
these four at 26.518 .
These numbers already updated in the IDL mosstat.pro code.

**Comment by dstndstn** [comment]
Done in 5beea62
