### ISSUE TITLE
Copilot plot during the night

### ISSUE THREAD

**Issue by dstndstn** [legacysurvey/obsbot#24]
this has the pass number in the second panel overlap the sky value. Could we put the sky value text of the last exposure just below the actual point? Also, is there some way of labeling the zero line with the “nominal” sky value? I suggest putting this in the middle of the plot just below the line. 

- it would be great to label the points in the exposure time panel with the depth factor,  perhaps by just adding a label above each point as it is plotted. That way if the depth factor is less than some number, we can ask the observers to log that in the bad_expid.txt file.  

- The transparency values between copilot and mosstat are still discrepant. Any idea why? Or did i just miss / not read a number of e-mails on this topic ;)

- Having copilot print out the dRA and dDec offsets needed to correct the pointing at the start of the night would be very useful. It is hard to find these numbers in the huge amount of ascii output, so i usually just eyeball it off the plot. It would be nice to have this listed somewhere on the plot.

**Comment by rblum5** [comment]
Does bullet three imply copilot and mosstat are now on the same astrometry?

**Comment by dstndstn** [comment]
Nope, not yet, but that is also no my list... actually, I just filed a ticket for it,
https://github.com/legacysurvey/obsbot/issues/26

**Comment by rblum5** [comment]
Cool! Once they are on the same reference frame, it is easy to keep telescope within a arcsec or so of optimal by watching the plot.

**Comment by dstndstn** [comment]
They're now on the same reference  frame.

adb8b54 starts the plot changes

**Comment by rblum5** [comment]
Great!

**Comment by dstndstn** [comment]
all done, except for the transparency discrepancy, which I'll handle in #27
